/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    collections: Collection;
    "archive-items": ArchiveItem;
    assets: Asset;
    transcripts: Transcript;
    narasumber: Narasumber;
    stories: Story;
    "batik-businesses": BatikBusiness;
    themes: Theme;
    locations: Location;
    "timeline-events": TimelineEvent;
    "color-map-entries": ColorMapEntry;
    "access-requests": AccessRequest;
    "access-grants": AccessGrant;
    "audit-logs": AuditLog;
    "payload-kv": PayloadKv;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    collections: CollectionsSelect<false> | CollectionsSelect<true>;
    "archive-items": ArchiveItemsSelect<false> | ArchiveItemsSelect<true>;
    assets: AssetsSelect<false> | AssetsSelect<true>;
    transcripts: TranscriptsSelect<false> | TranscriptsSelect<true>;
    narasumber: NarasumberSelect<false> | NarasumberSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    "batik-businesses":
      BatikBusinessesSelect<false> | BatikBusinessesSelect<true>;
    themes: ThemesSelect<false> | ThemesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    "timeline-events": TimelineEventsSelect<false> | TimelineEventsSelect<true>;
    "color-map-entries":
      ColorMapEntriesSelect<false> | ColorMapEntriesSelect<true>;
    "access-requests": AccessRequestsSelect<false> | AccessRequestsSelect<true>;
    "access-grants": AccessGrantsSelect<false> | AccessGrantsSelect<true>;
    "audit-logs": AuditLogsSelect<false> | AuditLogsSelect<true>;
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
    "payload-locked-documents":
      PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    "payload-preferences":
      PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    "payload-migrations":
      PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: "admin" | "editor" | "archivist" | "reviewer" | "researcher" | "member";
  mfaEnabled?: boolean | null;
  mfaSecret?: string | null;
  institution?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: "users";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections".
 */
export interface Collection {
  id: number;
  title: string;
  slug: string;
  subtitle?: string | null;
  descriptionShort: string;
  descriptionLong?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  region?: string | null;
  periodStart?: number | null;
  periodEnd?: number | null;
  status?: ("planned" | "active" | "completed") | null;
  /**
   * HANYA mitra dan pendana yang benar-benar terlibat. Jangan cantumkan logo lembaga yang belum bermitra (RULES §1.6).
   */
  funders?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archive-items".
 */
export interface ArchiveItem {
  id: number;
  /**
   * Format: AHI/BTP/2026/014
   */
  archiveNumber: string;
  title: string;
  /**
   * Tidak boleh diubah setelah terbit. Perubahan slug wajib disertai 301.
   */
  slug: string;
  collection: number | Collection;
  /**
   * 2–4 kalimat, kalimat pertama = jawaban (BLUF). Ini yang dikutip mesin jawaban.
   */
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  videoSource: "youtube" | "internal" | "none";
  /**
   * ID 11 karakter saja (dQw4w9WgXcQ), bukan URL penuh.
   */
  youtubeId?: string | null;
  /**
   * WAJIB dari cdn.arsiphidup.id. Hotlink ke i.ytimg.com merusak façade.
   */
  thumbnailUrl: string;
  youtubePrivacy?: ("public" | "unlisted") | null;
  internalAsset?: (number | null) | Asset;
  /**
   * Mirror publik di R2 untuk panel fallback (RULES V-11).
   */
  fallbackMp4?: string | null;
  durationSeconds: number;
  recordedAt: string;
  recordedPlace: string;
  language: ("id" | "jv" | "en")[];
  accessTier: "public" | "restricted";
  /**
   * Sebelum tanggal ini hanya metadata yang tampil (RULES E-5).
   */
  embargoUntil?: string | null;
  rightsStatement: string;
  license: string;
  /**
   * KODE dokumen saja (CNS-2026-014). Dokumen fisiknya TIDAK PERNAH diunggah ke sistem ini.
   */
  consentRef: string;
  consentVerified?: boolean | null;
  /**
   * Dicentang = seluruh item ditarik dari publik dalam ≤24 jam (RULES E-3).
   */
  withdrawalRequested?: boolean | null;
  contributors?:
    | {
        narasumber: number | Narasumber;
        role: "narasumber" | "pewawancara" | "juru-kamera" | "penerjemah";
        id?: string | null;
      }[]
    | null;
  themes?: (number | Theme)[] | null;
  location?: (number | null) | Location;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets".
 */
export interface Asset {
  id: number;
  archiveItem?: (number | null) | ArchiveItem;
  kind:
    | "video_full"
    | "video_highlight"
    | "video_story"
    | "audio"
    | "photo"
    | "photo_raw"
    | "document"
    | "transcript_file";
  tier: "public" | "restricted";
  altText?: string | null;
  caption?: string | null;
  /**
   * Verifikasi integritas jangka panjang. Bit rot itu nyata.
   */
  checksumSha256?: string | null;
  hlsManifestKey?: string | null;
  /**
   * Master TIDAK PERNAH dilayani lewat HTTP. Simpan di penyimpanan pelestarian.
   */
  isOriginalMaster?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "narasumber".
 */
export interface Narasumber {
  id: number;
  /**
   * Nama sebagaimana narasumber ingin disebut.
   */
  displayName: string;
  /**
   * Dipakai bila displayConsent = initials.
   */
  initials?: string | null;
  slug: string;
  honorific?: ("Ibu" | "Bapak" | "Mbah" | "Nyai" | "-") | null;
  bioShort?: string | null;
  bioLong?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * TAHUN saja. Tanggal lahir lengkap tidak dibutuhkan dan tidak disimpan.
   */
  birthYear?: number | null;
  roleTags?:
    | (
        | "pembatik"
        | "pewarna-alami"
        | "juragan"
        | "pedagang"
        | "tukang-cap"
        | "pengurus-komunitas"
      )[]
    | null;
  location?: (number | null) | Location;
  isDeceased?: boolean | null;
  deceasedYear?: number | null;
  /**
   * Dihormati di SETIAP tempat: judul, alt, meta OG, schema, URL. Bocor di satu titik = tidak ada anonimisasi.
   */
  displayConsent: "full_name" | "initials" | "anonymous";
  /**
   * Platform memfasilitasi perkenalan; kontak tidak pernah diberikan langsung (RULES E-2).
   */
  contactViaPlatformOnly?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes".
 */
export interface Theme {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transcripts".
 */
export interface Transcript {
  id: number;
  archiveItem: number | ArchiveItem;
  language?: ("id" | "jv" | "en") | null;
  format?: ("plain" | "timecoded" | "vtt") | null;
  body: string;
  segments?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Status ini DITAMPILKAN ke pembaca. Transkrip ASR yang tampak otoritatif lebih berbahaya daripada tidak ada transkrip (RULES C-4).
   */
  isVerified?: boolean | null;
  /**
   * Transkrip boleh publik meski videonya terbatas — penemuan maksimal, paparan minimal.
   */
  visibility?: ("public" | "restricted") | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "batik-businesses".
 */
export interface BatikBusiness {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-events".
 */
export interface TimelineEvent {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "color-map-entries".
 */
export interface ColorMapEntry {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-requests".
 */
export interface AccessRequest {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-grants".
 */
export interface AccessGrant {
  id: number;
  accessRequest: number | AccessRequest;
  user: number | User;
  scopeType: "collection" | "item" | "asset";
  scopeId: string;
  grantedAt: string;
  /**
   * Default 30 hari. Akses tanpa kedaluwarsa bukan akses terkendali.
   */
  expiresAt: string;
  revokedAt?: string | null;
  revokeReason?: string | null;
  maxDownloads?: number | null;
  downloadCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  occurredAt: string;
  actorUser?: (number | null) | User;
  /**
   * sha256(ip + user-agent + salt harian). Bukan IP.
   */
  actorHash?: string | null;
  eventType:
    | "video.play"
    | "video.complete"
    | "asset.signed_url_issued"
    | "asset.download"
    | "access_request.submitted"
    | "access_grant.approved"
    | "access_grant.revoked"
    | "login.success"
    | "login.failed"
    | "content.published"
    | "content.unpublished"
    | "narasumber.withdrawal";
  targetType?: string | null;
  targetId?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Menyimpan semuanya selamanya menciptakan liability yang tidak dibutuhkan.
   */
  retentionClass: "short" | "long";
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: "users";
        value: number | User;
      } | null)
    | ({
        relationTo: "collections";
        value: number | Collection;
      } | null)
    | ({
        relationTo: "archive-items";
        value: number | ArchiveItem;
      } | null)
    | ({
        relationTo: "assets";
        value: number | Asset;
      } | null)
    | ({
        relationTo: "transcripts";
        value: number | Transcript;
      } | null)
    | ({
        relationTo: "narasumber";
        value: number | Narasumber;
      } | null)
    | ({
        relationTo: "stories";
        value: number | Story;
      } | null)
    | ({
        relationTo: "batik-businesses";
        value: number | BatikBusiness;
      } | null)
    | ({
        relationTo: "themes";
        value: number | Theme;
      } | null)
    | ({
        relationTo: "locations";
        value: number | Location;
      } | null)
    | ({
        relationTo: "timeline-events";
        value: number | TimelineEvent;
      } | null)
    | ({
        relationTo: "color-map-entries";
        value: number | ColorMapEntry;
      } | null)
    | ({
        relationTo: "access-requests";
        value: number | AccessRequest;
      } | null)
    | ({
        relationTo: "access-grants";
        value: number | AccessGrant;
      } | null)
    | ({
        relationTo: "audit-logs";
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: "users";
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: "users";
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  mfaEnabled?: T;
  mfaSecret?: T;
  institution?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_select".
 */
export interface CollectionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  descriptionShort?: T;
  descriptionLong?: T;
  region?: T;
  periodStart?: T;
  periodEnd?: T;
  status?: T;
  funders?:
    | T
    | {
        name?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archive-items_select".
 */
export interface ArchiveItemsSelect<T extends boolean = true> {
  archiveNumber?: T;
  title?: T;
  slug?: T;
  collection?: T;
  summary?: T;
  description?: T;
  videoSource?: T;
  youtubeId?: T;
  thumbnailUrl?: T;
  youtubePrivacy?: T;
  internalAsset?: T;
  fallbackMp4?: T;
  durationSeconds?: T;
  recordedAt?: T;
  recordedPlace?: T;
  language?: T;
  accessTier?: T;
  embargoUntil?: T;
  rightsStatement?: T;
  license?: T;
  consentRef?: T;
  consentVerified?: T;
  withdrawalRequested?: T;
  contributors?:
    | T
    | {
        narasumber?: T;
        role?: T;
        id?: T;
      };
  themes?: T;
  location?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets_select".
 */
export interface AssetsSelect<T extends boolean = true> {
  archiveItem?: T;
  kind?: T;
  tier?: T;
  altText?: T;
  caption?: T;
  checksumSha256?: T;
  hlsManifestKey?: T;
  isOriginalMaster?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transcripts_select".
 */
export interface TranscriptsSelect<T extends boolean = true> {
  archiveItem?: T;
  language?: T;
  format?: T;
  body?: T;
  segments?: T;
  isVerified?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "narasumber_select".
 */
export interface NarasumberSelect<T extends boolean = true> {
  displayName?: T;
  initials?: T;
  slug?: T;
  honorific?: T;
  bioShort?: T;
  bioLong?: T;
  birthYear?: T;
  roleTags?: T;
  location?: T;
  isDeceased?: T;
  deceasedYear?: T;
  displayConsent?: T;
  contactViaPlatformOnly?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "batik-businesses_select".
 */
export interface BatikBusinessesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes_select".
 */
export interface ThemesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-events_select".
 */
export interface TimelineEventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "color-map-entries_select".
 */
export interface ColorMapEntriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-requests_select".
 */
export interface AccessRequestsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-grants_select".
 */
export interface AccessGrantsSelect<T extends boolean = true> {
  accessRequest?: T;
  user?: T;
  scopeType?: T;
  scopeId?: T;
  grantedAt?: T;
  expiresAt?: T;
  revokedAt?: T;
  revokeReason?: T;
  maxDownloads?: T;
  downloadCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  occurredAt?: T;
  actorUser?: T;
  actorHash?: T;
  eventType?: T;
  targetType?: T;
  targetId?: T;
  metadata?: T;
  retentionClass?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: "full";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
